# SOPS configuration for encrypted secrets
#
# To add a new host:
#   1. Get the host's SSH public key: ssh-keyscan <hostname> 2>/dev/null | grep ed25519
#   2. Convert to age: ssh-to-age -i /path/to/ssh_host_ed25519_key.pub
#   3. Add the age key to this file under 'keys'
#   4. Create secrets/<hostname>.yaml
#   5. Run: sops secrets/<hostname>.yaml
#
# To edit secrets: sops secrets/<hostname>.yaml

keys:
  # Admin keys (can decrypt all secrets)
  # Add your personal age key here:
  # - &admin_joost age1...

  # Host keys (derived from SSH host keys using ssh-to-age)
  # Run: ssh-to-age -i /etc/ssh/ssh_host_ed25519_key.pub
  - &hetzner-dev age1PLACEHOLDER_RUN_ssh-to-age_ON_HOST
  - &github-runner-01 age1k77q70qv8h6kp7n8pw92mcyww62xkmwps50mknmzdjwn6s29wu2s3gav4w
  - &github-runner-02 age1p26cwwyu2v4jexue6z7krrua9skqv0p3aj4ad3su4m7varky3dwqk0zphj

creation_rules:
  # hetzner-dev secrets
  - path_regex: secrets/hetzner-dev\.yaml$
    key_groups:
      - age:
          - *hetzner-dev
          # - *admin_joost  # Uncomment after adding admin key

  # github-runner-01 secrets (GitHub runner token)
  - path_regex: secrets/github-runner-01\.yaml$
    key_groups:
      - age:
          - *github-runner-01
          # - *admin_joost  # Uncomment after adding admin key

  # github-runner-02 secrets (GitHub runner token)
  - path_regex: secrets/github-runner-02\.yaml$
    key_groups:
      - age:
          - *github-runner-02
          # - *admin_joost  # Uncomment after adding admin key
