# Hardware configuration for Hetzner server (loom-32gb-nbg1-1)
# Generated by 'nixos-generate-config' on 2026-01-30
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/profiles/qemu-guest.nix")
    ];

  boot.initrd.availableKernelModules = [ "ahci" "virtio_pci" "virtio_scsi" "sd_mod" "sr_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/82064483-7c40-41f8-b809-eae4ee9230fd";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/6505-15E7";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/5f489149-eb5e-494c-8176-c18eba7a7918"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
}
