name: Flake ❄️ Lock 🔒️ Updater ✨

on:
  schedule:
    # Pi o'clock
    - cron: "3 14 * * 1,5"
  workflow_dispatch:

jobs:
  lock-updater:
    name: Flake Lock Updater
    runs-on: ubuntu-22.04
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v7.0.1
        with:
          persist-credentials: false
      - uses: DeterminateSystems/determinate-nix-action@v3.21.9
      - uses: DeterminateSystems/update-flake-lock@v28
        with:
          branch: automated/flake-lock-updates
          pr-title: "chore: update flake.lock"
          pr-labels: dependencies
